### PR TITLE
sample secret manager service account key management solution in Pyth…

### PR DESCRIPTION
**Pull request by hilliao**
Proposed sample code contribution for [secret manager service account key management solution in Python 3.8](https://github.com/hilliao/enterprise-solutions/tree/master/googlecloud/sa-keys)

1. @googlebot Accenture contributed to the solution. An Accenture managing director at Accenture Google cloud business group signed the CLA on 4/1/2019. I have a PDF to prove it. Please share who I can share the PDF with to hil.liao@accenture.com if verification is required.
2. Please advise who at Google is in charge of accepting my pull request. I can share or do a live demo on the solution deployed in a production environment over Google Meet. Please contact me at hil.liao@accenture.com for setting up the Meet.

### CODE REVIEW

**Comment by hilliao** [comment]
1. @googlebot Accenture contributed to the solution. An Accenture managing director at Accenture Google cloud business group signed the CLA on 4/1/2019. I have a PDF to prove it. Please share who I can share the PDF with to hil.liao@accenture.com if verification is required.
2. Please advise who at Google is in charge of accepting my pull request. I can share or do a live demo on the solution deployed in a production environment over Google Meet. Please contact me at hil.liao@accenture.com for setting up the Meet.

**Comment by hilliao** [comment]
@googlebot I signed it!

**Comment by sethvargo** [comment]
Storing Google service account keys in Secret Manager is highly frowned upon, and this pattern is basically privilege escalation as a service.

**Comment by leahecole** [comment]
Citing @sethvargo, I'm going to close this PR because this is not recommended behavior for the service.

**Pull request closed without merging**
