### PR TITLE
Updated samples with etag support

### PR DESCRIPTION
**Pull request by gwhitehawk**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-secret-manager/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x ] Code coverage does not decrease (if any source code was changed)
- [x ] Appropriate docs were updated (if necessary)

Fixes https://github.com/googleapis/python-secret-manager/issues/129 🦕

### CODE REVIEW

**Comment by leahecole** [comment]
It seems like lint and the tests are failing - @gwhitehawk please feel free to ping me if you need help debugging these failures from the Python side. I'm not a secret manager expert but can give general python samples advice :) 

@sethvargo if you can just give this glance and make sure everything seems appropriately "secret-manager-y" that would also be appreciated

**Comment by gwhitehawk** [comment]
Thanks for pointing out the problems - I fixed the import issues. Still haven't run unit tests - I can't set up authentication with keys for my service account (as an internal). Can you please re-apply kokoro force-run label?

**Review by sethvargo — APPROVED** [review]

**Comment by gwhitehawk** [comment]
@leahecole Seth seemed to appprove but not sure whether he has permission to write. Could you please take another look at the changes? Thanks.

**Comment by gwhitehawk** [comment]
This is ready for re-review. I set up external non-google project and ran tests locally.

**Review by leahecole — APPROVED** [review]

**Pull request merged**
